---
- name: install doom emacs
  shell: ~/.emacs.d/bin/doom -y install

- name: sync doom emacs
  shell: ~/.emacs.d/bin/doom -y sync

- name: restart emacs
  systemd:
    name: emacs
    state: restarted
    enabled: True
    scope: user
